:feat: Implement and update cat commands
Diaga/Distributed-Finder pull request #36
Opened 2020-11-26 22:48 UTC by EeshaArif

- Update rm command to remove data in sectors
- Update cat_end command for parsed entries
- Implement cat command

close #20

2020-11-26 23:09 UTC, EeshaArif commented on commands/cat_end.py
>              raise ValueError('InvalidEntry: File does not exist')
Let me know if these checks are redundant and have been taken care of in the parse()

2020-11-26 23:10 UTC, EeshaArif commented on commands/cat_end.py
> +        if (FileDao.is_unique_filename(file.name, file_directory)
Let me know if these checks are redundant and have been taken care of in the parse()

2020-11-27 09:29 UTC, Diaga requested changes
Some small changes, looks good otherwise!

2020-11-27 09:29 UTC, Diaga commented on commands/cat.py
> +            file.directory_id)
You can do `file.directory`

2020-11-27 09:29 UTC, Diaga commented on commands/cat.py
> +        if (FileDao.is_unique_filename(file.name, file_directory)
We do not need these checks, `context.parse` will raise errors if the file does not exist.

2020-11-27 09:29 UTC, Diaga commented on commands/cat_end.py
> +        file_directory = DirectoryDao.get_directory_from_directory_id(
Same as above, `file.directory`

2020-11-27 09:29 UTC, Diaga commented on commands/cat_end.py
> +                or not FileDao.is_valid_filename(file.name)):
Same as above, we do not need these checks

2020-11-27 10:59 UTC, Diaga approved these changes
Looks good, thanks~

2020-11-27 10:59 UTC, merged